/* Fetch angular from the browser scope */
var angular = window.angular;

/**
 * Directives module.
 * @module Directives
 */
var Directives = angular.module('Directives', [
    'role',
    'rolebar',
    'alertbar',
    'plan',
    'Item',
    'Event',
    'Events',
    'Play',
    'Plays',
    'team-info',
    'date',
    'AddTime',
    'no-results',
    'videoplayer',
    'sport-placeholder',
    'role-icon',
    'add-player',
    'mascot-placeholder',
    'profile-placeholder',
    'NotesList',
    'positionsDropdown',
    'uploader',
    'FeedbackModal',
    'FormationChart',
    'Arena',
    'roster-manager',
    'loading',
    'thumbnail',
    'OpenModal',
    'OpenModalText',
    'OpenModalConfirm',
    'OpenModalAlert',
    'DynamicTable',
    'user-typeahead',
    'Videogular'
]);

require('role');
require('rolebar');
require('alertbar');
require('plan');
require('item');
require('event');
require('events');
require('play');
require('plays');
require('team-info');
require('date');
require('add-time');
require('no-results');
require('videoplayer');
require('sport-placeholder');
require('role-icon');
require('add-player');
require('roster');
require('athlete');
require('coach-info');
require('thumbnail');
require('film');
require('mascot-placeholder');
require('profile-placeholder');
require('notes-list');
require('positions-dropdown');
require('uploader');
require('roster-manager');
require('loading');
require('feedback-modal');
require('formation-chart');
require('arena');
require('open-modal');
require('open-modal-text');
require('open-modal-confirm');
require('open-modal-alert');
require('dynamic-table');
require('user-typeahead');
require('videogular');
