/* Fetch angular from the browser scope */
var angular = window.angular;

/**
 * Directives module.
 * @module Directives
 */
var Directives = angular.module('Directives', [
    'role',
    'rolebar',
    'RoleIcon',
    'alertbar',
    'plan',
    'Item',
    'Event',
    'Events',
    'Play',
    'Playlist',
    'team-info',
    'date',
    'AddTime',
    'results',
    'no-results',
    'videoplayer',
    'sport-placeholder',
    'arena-placeholder',
    'add-resource',
    'mascot-placeholder',
    'profile-placeholder',
    'NotesList',
    'positionsDropdown',
    'stateSelector',
    'uploader',
    'FeedbackModal',
    'FormationChart',
    'Arena',
    'xy-coordinates',
    'managers',
    'loading',
    'thumbnail',
    'OpenModal',
    'OpenModalText',
    'OpenModalConfirm',
    'OpenModalAlert',
    'DynamicTable',
    'team-typeahead',
    'user-typeahead',
    'VerifyPassword',
    'Videogular',
    'BreakdownText',
    'Videogular',
    'PlayerInformation',
    'FilmHomeTabs',
    'PlaysFilters',
    'athlete',
    'uploadingControls',
    'uploadStatus',
    'kvsUploader',
    'Profile',
    'PlaysFilters',
    'Draggable',
    'Sidebar'

]);

require('role');
require('rolebar');
require('alertbar');
require('plan');
require('item');
require('event');
require('events');
require('play');
require('playlist');
require('team-info');
require('date');
require('add-time');
require('results');
require('no-results');
require('videoplayer');
require('sport-placeholder');
require('arena-placeholder');
require('role-icon');
require('add-resource');
require('athlete');
require('coach-info');
require('thumbnail');
require('film');
require('mascot-placeholder');
require('profile-placeholder');
require('notes-list');
require('positions-dropdown');
require('state-selector');
require('uploader');
require('managers');
require('loading');
require('feedback-modal');
require('formation-chart');
require('xy-coordinates');
require('arena');
require('open-modal');
require('open-modal-text');
require('open-modal-confirm');
require('open-modal-alert');
require('dynamic-table');
require('team-typeahead');
require('user-typeahead');
require('verify-password');
require('videogular');
require('breakdown-text');
require('film-home-tabs');
require('profile');
require('player-information');
require('plays-filters');
require('uploading-controls');
require('upload-status');
require('kvs-uploader');
require('draggable');
require('sidebar');


